# Generated by Django 3.1.7 on 2021-04-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='x',
            new_name='x1',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='y',
            new_name='x2',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='y1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='y2',
            field=models.IntegerField(default=0),
        ),
    ]
